all URIs must be of type CDATA (cdata-fix)
publica-project/vast pull request #3
Opened 2017-07-29 01:36 UTC by nabhanelrahman

2017-07-29 02:09 UTC, kalbasit requested changes

2017-07-29 02:09 UTC, kalbasit commented on extension_test.go
> +	extensionCustomTracking = []byte(`<Extension type="testCustomTracking"><CustomTracking><Tracking event="event.1"><![CDATA[http://event.1]]></Tracking><Tracking event="event.2"><![CDATA[http://event.
let's add another test asserting without `CDATA`.

2017-07-29 02:09 UTC, kalbasit commented on vast.go
> +	NonLinearClickTracking []CDATA `xml:",omitempty"`
did you try `NonLinearClickTracking []string `xml:",cdata,omitempty`? Try adding a test with it withCDATA and without. If it works, please change all of them and remove the `CDATA` struct

2017-07-30 07:31 UTC, nabhanelrahman commented on extension_test.go
> +	extensionCustomTracking = []byte(`<Extension type="testCustomTracking"><CustomTracking><Tracking event="event.1"><![CDATA[http://event.1]]></Tracking><Tracking event="event.2"><![CDATA[http://event.
@kalbasit TestSpotXVpaid also tests CDATA

2017-07-30 07:34 UTC, closed without merging